# Generated by Django 4.2.3 on 2023-12-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(max_length=200)),
                ('img_url', models.URLField()),
                ('price', models.FloatField(max_length=200)),
                ('initial_stock', models.IntegerField()),
                ('actual_stock', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=200)),
                ('primary_color', models.CharField(max_length=200)),
                ('secondary_color', models.CharField(max_length=200)),
                ('brand', models.CharField(default='', max_length=200)),
                ('size', models.CharField(max_length=4)),
            ],
        ),
    ]
