# Generated by Django 4.2.3 on 2023-12-05 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='url',
        ),
    ]
