# Generated by Django 4.2.3 on 2023-12-06 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0005_alter_cartitem_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='CartProduct',
        ),
    ]
